<?php

namespace Georgechem\SqliteDb\Model;

use PHPUnit\Framework\TestCase;

/**
 * @covers Storage
 */
class StorageTest extends TestCase
{
    private Storage $storage;

    public function setUp():void
    {
        parent::setUp();
        $this->storage = new Storage();

    }

    public function testIsProperInstance()
    {
        self::assertInstanceOf(Storage::class, $this->storage, 'is proper instance');
    }

    public function testIsStorageCreated()
    {
        $result = $this->storage->create();
        self::assertEquals(true, $result, 'true if storage created successfully or already exists');

    }

    public function testIsStorageDestroyed()
    {
        $result = $this->storage->destroy();
        self::assertEquals(true, $result, 'true if store destroyed successfully');
    }



    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}